fsw/public_inc/sample_lib.h, fsw/src/sample_lib.c
Fix #8
In order to make a useful library unit test example, the sample_lib itself needs to perform some more interesting work.
In particular it needs at least one external function call on which a code path decision is made, such that the example UT code will have more than one code path to demonstrate.
Additionally, the library should have some internal "global" structure (like real libs would) that contains its state, that the UT can also test/query.
Both objectives can be accomplished with a small string buffer that gets populated with a `strncpy()` call during init, and printed with the "process" command.
Other minor updates for correctness:
- The entry point (`SAMPLE_LibInit`) is not really a "private" function.  It is called from ES when starting up. …
=> Add logic to sample_lib for UT

fsw/public_inc/sample_lib.h, fsw/src/sample_lib.c
Fix #8
1. Checked out all IC 20191230 branches
1. Built and ran cFS unit tests and OSAL coverage (vxworks and shared)
1. All passed (although osal_timer_UT occasionally still fails due to a test issue)
1. Make cmdUtils where cFS-GroundSystem expects it
1. cd tools/cFS-GroundSystem/Subsystems/cmdUtil
1. make
1. Started Ground system
1. python3 GroundSystem.py
1. Enabled commands to 127.0.0.1
1. Confirmed telemetry packets received
1. Sent ES and TIME noop commands, confirmed noop message from cFS on Port 1
1. Sent ES power on reset and observed cFS exit
See related pull requests
- cFS Dev Server 2
- Versions: ic-20191230 branches
N/A …
=> Integration Candidate 20191230

unit-test/CMakeLists.txt
OSAL now sets these as UT_COVERAGE_COMPILE_FLAGS, UT_COVERAGE_LINK_FLAGS.
Building and linking the UT executable needs a corresponding update.
Fixes #19 
Build with `ENABLE_UNIT_TESTS=TRUE` and confirm that all unit tests are building
Coverage data (`make lcov`) now includes the sample_lib code again
Ubuntu 18.04 LTS 64 bit
=> Fix #19, Update coverage compile/link flag options

README.md, fsw/src/sample_lib_version.h
Fixes #19
See PRs
Bundle CI - https://github.com/nasa/cFS/pull/74/checks?check_run_id=637311464
PR #20 - Coverage data `make lcov` includes the sample_lib code
See PRs
Bundle CI - Ubuntu:Bionic
Part of https://github.com/nasa/cFS/pull/74
=> Integration Candidate: 2020-04-22

fsw/public_inc/sample_lib.h, fsw/src/sample_lib.c, fsw/src/sample_lib_internal.h, fsw/src/sample_lib_version.h, unit-test/coveragetest/coveragetest_sample_lib.c, unit-test/coveragetest/sample_lib_coveragetest_common.h, unit-test/inc/OCS_string.h, unit-test/override_inc/string.h, unit-test/override_src/libc_string_stubs.c, ut-stubs/sample_lib_stubs.c
Whitespace changes only.
Fix #15 
CI - https://travis-ci.com/github/skliper/cFS/builds/167637651
None
- Hardware: CI
- Versions: Bundle w/ all whitespace change commits
Note - not enforcing, just a single cleanup since there's no pending activity in this repo.
None
=> Fix #15, Apply standard style

README.md, fsw/public_inc/sample_lib.h, fsw/src/sample_lib.c, fsw/src/sample_lib_internal.h, fsw/src/sample_lib_version.h, unit-test/coveragetest/coveragetest_sample_lib.c, unit-test/coveragetest/sample_lib_coveragetest_common.h, unit-test/inc/OCS_string.h, unit-test/override_inc/string.h, unit-test/override_src/libc_string_stubs.c, ut-stubs/sample_lib_stubs.c
Fix #15 
See PR #23 
Bundle CI - https://travis-ci.com/github/nasa/cFS/builds/168822512
None
Ubuntu:Bionic
**Additional Context**
Part of nasa/cFS#91
Jacob Hageman, NASA-GSFC
=> Integration Candidate: 2020-05-20

README.md, unit-test/CMakeLists.txt
Fix #26
- Install unit test as part of cmake recipe
Normal build with ENABLE_UNIT_TESTS=true, with make install, and ran sample lib unit test from install dir (passed)
Sample lib test runner now shows up in expected  install dir
- Hardware: cFS Dev VM
- Versions: current bundle development branch
None.
None.
=> Fix #26, Install unit test

fsw/src/sample_lib.c, fsw/src/sample_lib_version.h
Close #25 
Build with bundle
Version report now shows development build number
```
1980-012-14:06:58.26153 ES Startup: Loading shared library: /cf/sample_lib.so
SAMPLE Lib Initialized. Sample Lib Development Build v1.1.0+dev26, Last Official Release: v1.1.0
```
Ubuntu on Docker on OSX
None
None
Gerardo E. Cruz-Ortiz, NASA-GSFC
=> Close #25, Add build number and baseline to version file

README.md, fsw/src/sample_lib.c, fsw/src/sample_lib_version.h, unit-test/CMakeLists.txt
Fix #26
Close #25
Bundle CI - https://github.com/nasa/cFS/pull/119/checks
PR #27 - Install unit test as part of cmake recipe. Sample lib test runner now shows up in expected install directory
PR #29 - Add development build number and baseline to version reporting
Ubuntu
Part of nasa/cfs#119
None
Jacob Hageman, NASA-GSFC
Gerardo E. Cruz-Ortiz, NASA-GSFC
=> Integration Candidate 2020-07-29

unit-test/CMakeLists.txt
Fix #30, Install unit test to target directory
Make unit tests, install, observe they install in correct directory
Correct install directory
- Hardware: cFS Dev Server
- Versions: Bundle main + this commit
None.
None
=> Fix #30, Install unit test to target directory

README.md, fsw/src/sample_lib_version.h, unit-test/CMakeLists.txt
Fix #30 
Bundle CI - https://github.com/nasa/cFS/pull/140/checks
PR #31 - Installs unit test to target directory.
Ubuntu - CI
https://github.com/nasa/cFS/pull/140
Jacob Hageman, NASA-GSFC
=> Integration Candidate: 2020-09-16

fsw/public_inc/sample_lib.h, fsw/src/sample_lib.c, fsw/src/sample_lib_internal.h, unit-test/coveragetest/coveragetest_sample_lib.c, ut-stubs/sample_lib_stubs.c
Replace inconsistent SAMPLE_ And SAMPLE_Lib prefixes, now all identifiers should start with SAMPLE_LIB_.
Fixes #33 
Build and sanity test CFE
Run all unit tests
No impact to behavior, but this also changes the name of the init function from `SAMPLE_LibInit` to `SAMPLE_LIB_Init` which affects the CFE startup script.
Ubuntu 20.04
Needs to be merged with nasa/sample_app#100
=> Fix #33, Standardize to SAMPLE_LIB_ namespace prefix

README.md, fsw/public_inc/sample_lib.h, fsw/src/sample_lib.c, fsw/src/sample_lib_internal.h, fsw/src/sample_lib_version.h, unit-test/coveragetest/coveragetest_sample_lib.c, ut-stubs/sample_lib_stubs.c
Fix #33, Standardize to SAMPLE_LIB_ namespace prefix
See framework-bundle CI: https://github.com/nasa/cFS/pull/154/checks
PR #34 -  No behavior changes. All identifiers now use the prefix `SAMPLE_LIB_`. Changes the name of the init function from SAMPLE_LibInit to SAMPLE_LIB_Init which affects the CFE startup script.
Ubuntu CI 
Part of https://github.com/nasa/cFS/pull/154
None
@jphickey
=> Integration Candidate: 2020-11-03

unit-test/coveragetest/coveragetest_sample_lib.c
Describe the contribution
Fixes #36 by changing UT_SetForceFail to UT_SetDefaultReturnValue
Testing performed
Build and run unit test
Expected behavior changes
No impact to behavior
System(s) tested on
Ubuntu 20.04
Additional context
Dependant on nasa/osal#646
Contributor Info - All information REQUIRED for consideration of pull request
Alex Campbell - NASA/GSFC
=> Fix #36, Refactor UT_SetForceFail to UT_SetDefaultReturnValue

README.md, fsw/src/sample_lib_version.h, unit-test/coveragetest/coveragetest_sample_lib.c
Fix #36, Refactor UT_SetForceFail to UT_SetDefaultReturnValue
See events for "github actions test" at <https://github.com/astrogeco/cFS/actions>
PR #37 - Rename `UT_SetForceFail` to `UT_SetDefaultReturnValue` since some functions that retain more than 1 value are not necessarily failing
Ubuntu 18.04
Part of <https://github.com/nasa/cFS/pull/158>
None
@zanzaben
=> sample_lib Integration Candidate: 2020-11-24

SECURITY.md
Fix #39 
Created a draft of a security policy markdown file for sample_lib. The purpose of a security policy is to inform users on how to submit bugs or vulnerabilities. It is ideal to include a section for supported versions.
Optional sections that may be included:
- What to expect security-wise such as what type of testing is done
- Address privacy concerns
- Supported versions
- License
- Known vulnerabilities
References to Public Security Policies:
https://github.com/thanos-io/thanos/security/policy
https://github.com/minhealthnz/nzcovidtracer-app/security/policy
https://github.com/odoo/odoo/security/policy
Ariel Adams, ASRC Federal
=> Fix #39, Create Security Policy

.github/workflows/codeql-build.yml
Fix #44 - adds CodeQL analysis
Differences from bundle - just builds sample_lib, has timeout
Ran on fork
Adds Code QL analysis on push to main and pull requests (to main)
CI
None
None
=> Fix #44, Add CodeQL analysis to workflow

CMakeLists.txt, unit-test/CMakeLists.txt, ut-stubs/CMakeLists.txt
Use the wrapper functions now provided by CFE to simplify the
build recipe and work with interface libraries
Fixes #46
Build and run CFE unit tests
Unit test targets are named a little differently when using the wrapper functions, but transparent if running via ctest.  The filename is different if running manually though.
Ubuntu 20.04
Requires nasa/cfe#1207 and must be merged before nasa/cfe#1203 to avoid breaking UT
=> Fix #46, simplify build to use wrappers and interface libs

SECURITY.md
Fix #48
Updated the Security Policy to include the type of testing done for sample_lib or the cFS bundle under a new section titled "Testing". Provided a disclaimer that under the Apache license, liability is not provided. 
Added that security reports should be emailed. 
Users should now be aware of the type of testing sample_lib or the cFS bundle undergoes. 
References: 
https://github.com/thanos-io/thanos/security/policy
https://github.com/phpMussel/phpMussel/security/policy
https://github.com/timberio/vector/security/policy
Ariel Adams, ASRC Federal
=> Fix #48, Add Testing Tools to the Security Policy

fsw/src/sample_lib_internal.h, unit-test/coveragetest/coveragetest_sample_lib.c, unit-test/coveragetest/sample_lib_coveragetest_common.h, unit-test/override_inc/string.h, unit-test/override_src/libc_string_stubs.c
Fix #51 - uses `"` for local includes
Build/run unit tests, passed
None
- Hardware: cFS Dev Server
- Versions: Bundle main + this commit
None
Full name and company/organization/center of all contributors ("Personal" if individual work)
- If NASA Civil Servant Employee or GSFC Contractor on SES II
- Address/email/phone and contract/task information (if applicable) must be on file
- Else if Company
- **HAND SIGNED** Company CLA must be on file (once per release): [Company …
=> Fix #51, Use quotes for local includes

CONTRIBUTING.md
Fix #52 
Added a contributing guide that links to the main cFS contributing guide. 
Users should be able to view the contributing guide contents easily from the sample_lib repo. 
Ariel Adams, ASRC Federal
=> Fix #52, Add Contributing Guide

CONTRIBUTING.md, README.md, fsw/src/sample_lib_internal.h, fsw/src/sample_lib_version.h, unit-test/coveragetest/coveragetest_sample_lib.c, unit-test/coveragetest/sample_lib_coveragetest_common.h, unit-test/override_inc/string.h, unit-test/override_src/libc_string_stubs.c
Fix #51, Use " for local includes
Fix #52, Added a contributing guide that links to the main cFS contributing guide.
See https://github.com/nasa/cFS/pull/223/checks
Replace `<>` with `"` for local includes
Adds `CONTRIBUTING.md` that links to the main cFS contributing guide.
- Hardware: [e.g. PC, SP0, MCP750]
- OS: [e.g. Ubuntu 18.04, RTEMS 4.11, VxWorks 6.9]
- Versions: [e.g. cFE 6.6, OSAL 4.2, PSP 1.3 for mcp750, any related apps or tools]
Part of https://github.com/nasa/cFS/pull/223
None
@ArielSAdamsNASA 
@skliper
=> sample_lib Integration candidate: 2021-03-23

unit-test/coveragetest/coveragetest_sample_lib.c
The UT_Hook_GetArgValueByName macro provided by UT assert is the preferred way to get an argument in the current version.  Reading the pointer directly is not advised as it depends on how the stub was actually implemented, whereas the macro should produce consistent results.
Fixes #59
Build and run all unit tests, confirm sample_lib test works
Hook will continue to work even if stub implementation changes.
Ubuntu 20.04
Using macro is more readable, more future proof, and reflects current best practice for UT assert hooks.
=> Fix #59, replace direct ref to ArgPtr with macro

README.md, fsw/src/sample_lib_version.h, unit-test/coveragetest/coveragetest_sample_lib.c
Fix #59, replace direct ref to ArgPtr with macro 
The UT_Hook_GetArgValueByName macro provided by UT assert is the preferred way to get an argument in the current version. Reading the pointer directly is not advised as it depends on how the stub was actually implemented, whereas the macro should produce consistent results.
Hook will continue to work even if stub implementation changes.
Using macro is more readable, more future proof, and reflects current best practice for UT assert hooks.
Part of <https://github.com/nasa/cfs/pull/250>
sample_lib Tests <https://github.com/nasa/sample_lib/pull/61/checks>
cFS Bundle Tests <https://github.com/nasa/cfs/issues/250/checks>
@jphickey
=> sample_lib Integration candidate: 2021-04-27

.github/workflows/codeql-build.yml
Fix #62
Added the duplicate jobs action to avoid duplicate jobs from running. Added a separate job for coding standard queries. Created two configuration files, one for default queries and security queries and another for jpl rules. Removed push on main branch so when users push code to their forked repos, the workflow runs. Added main branch to pull request, so CodeQL runs on pull request made in the main branch. This is the same logic used in the cFS bundle repo. 
Testing done on cFE forked repository, ArielSAdamsNASA/cFE which used the same files, but with different configuration paths.
Jobs were failing when the entire path of the configuration file were not used. Have to use nasa/cFE/.github/codeql/config-name@branch-name. The …
=> Fix #62, Implement Coding Standard CodeQL

SECURITY.md, unit-test/CMakeLists.txt, unit-test/coveragetest/coveragetest_sample_lib.c, unit-test/override_src/libc_string_stubs.c
Fixed a few minor typos in the text of SECURITY.md, and in the comments of:
- unit-test/CMakeLists.txt
- libc_string_stubs.c 
None (non-executable code).
None (minor Markdown doc and comments changes only).
n/a
n/a
**Code contributions**
n/a
=> Corrected minor markdown and comment typos

README.md, fsw/src/sample_lib_version.h
Update baseline to cFS-Caleum-rc4: v1.3.0-rc4
Update mission rev to use 0xFF for development version
- sample_lib Checks <https://github.com/nasa/sample_lib/pull/73/checks>
- cFS Bundle Checks <https://github.com/nasa/cFS/pull/390/checks>
None
Ubuntu 18.04
Part of <https://github.com/nasa/cFS/pull/390>
None
@astrogeco
=> Update Build Baseline to cFS-Caelum-rc4

fsw/public_inc/sample_lib.h, fsw/src/sample_lib_internal.h, unit-test/coveragetest/sample_lib_coveragetest_common.h, unit-test/inc/OCS_string.h, unit-test/override_inc/string.h
- Fix #58
CI
None
CI
None
None
=> Fix #58, Apply header guard standard

fsw/src/sample_lib_version.h
- Fix #75 
Make doc, observe no filename warnings
None
- Hardware: i5/wsl
- Versions: Bundle main + this commit
None
None
=> Fix #75, Remove explicit filename doxygen comments
